### PR TITLE
fix a memory leak

### PR DESCRIPTION
**Pull request by Dellynyaa**

### CODE REVIEW

**Comment by nemuibanila** [comment]
For now, this doesn't actually leak any memory in the context of nya being a short-lived command line utility; the OS will generally free all resources associated with "nya" at exit.

**Comment by TudbuT** [comment]
stll id argue its bad practice to rely on that so i think a PR does make sense here

**Comment by Dellynyaa** [comment]
yep, i know of this, but as tudbut said, i don't particularly like relying on it.

**Comment by JessSystemV** [comment]
oh god maintaining the AUR for this... y'all...

**Pull request merged**
